version: 2.0
orbs:
  aws-cli: circleci/aws-cli@0.1.15
jobs:
  build:
    docker:
      - image: josephpaulmckenzie/serverless-testing
    steps:
      - checkout
      - run:
          name: Determine which projects have changed and trigger the builds
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              bash scripts/identify-modified-directories.sh
              bash scripts/build_projects.sh
            else
              echo -e "Not master branch, did not run circleci build process"
            fi
  service1:
    docker:
      - image: josephpaulmckenzie/serverless-testing
    steps:
      - checkout
      - run:
          name: Start Build for service1
          command: |
            # echo -e "sls install"
            # sudo npm i -g serverless
            echo -e "go into project folder"
            cd service1
            npm install
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=us-east-1
            echo -e "sls deploy new commit"
            serverless deploy
  