version: 2.0
orbs:
  aws-cli: circleci/aws-cli@0.1.15
jobs:
  build:
    docker:
      - image: josephpaulmckenzie/serverless-testing
    steps:
      - checkout
      - run:
          name: Determine which projects have changed and trigger the builds
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              bash scripts/identify-modified-directories.sh
              bash scripts/build_projects.sh
            else
              echo -e "Not master branch, did not run circleci build process"
            fi
  service1:
    steps:
      - checkout
      - run:
          name: Start Build for service1
          command: |
            bash scripts/serverless-deploy.sh service1

  