version: 2
jobs:
  build:
    docker:
      - image: josephpaulmckenzie/serverless-testing
    steps:
      - checkout
      - run:
          name: Determine which projects have changed and trigger the builds
          command: |
            bash scripts/identify-modified-directories.sh
            bash scripts/build_projects.sh

  service1:
    working_directory: circleci-monorepo/service1
    docker:
      - image: josephpaulmckenzie/serverless-testing
    environment:
      PROJECT_NAME: service1
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install Needed Packages 
          command: |
            npm install
      - run:
          name: Run Tests
          command: |
            # /scripts/go_test.sh ${TEST_RESULTS} ${PROJECT_NAME}
      - run:
          name: Deploy to AWS 
          command: |
            sls deploy
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
  service2:
    working_directory: circleci-monorepo/service2
    docker:
      - image: josephpaulmckenzie/serverless-testing
    environment:
      PROJECT_NAME: service2
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install Needed Packages 
          command: |
            npm Install
      - run:
          name: Run Tests
          command: |
            # /scripts/go_test.sh ${TEST_RESULTS} ${PROJECT_NAME}
      - run:
          name: Deploy to AWS 
          command: |
            # /scripts/go_build.sh ${PROJECT_NAME} ${PROJECT_NAME}
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results